[package]
name = "graphic-env"
version = "0.1.5"
edition = "2024"

[dependencies]
anyhow = "1.0.102"	# used for simple error handling 
log = "0.4.29"		# used for logging statement
cgmath = "0.18.0"	# used as a Rust replacement for GLM (graphics math library)
pretty_env_logger = "0.5.0"	# used to print our logs to the console 
thiserror = "2.0.18"		# used to define custom errors types without boilerplate
vulkanalia = { version = "=0.35.0", features = ["libloading", "provisional", "window"] } # used to call the Vulkan API
winit = "0.29.15" # used to create a window to render to
rand = "0.10.1"
itertools = "0.14.0"

# i/o dependencies
tobj = { version = "4.0.3", features = ["log"] } # used to load 3D models in the Wavefront .obj format
png = "0.18.1"		# used to load PNGs to use as textures
gltf = "1.4.1"      # used to load glTF obj
ktx2 = "0.5.0"      # used to load KTX2 compressed texture format
basis-universal = "0.3.1"
